- client.js
persist.js test was failing with "dht is already listening", when lookup() was issued while _binding==true && listening==false
> defer lookup when still binding

- client.js
- test/dht_store_mutable.js
This patch adds some tests for sequences and should fix #66. Previously, the hash was used for lookups before it was computed.
> seq put fix

- client.js
- test/dht_store_immutable.js
this should fix BEP44 when putting/getting keys in the public bittorrent dht which currently doesn't work.
the spec is vague on how putting of keys work but after reading the libtorrent source code and pinging some bittorrent devs on irc it turns out you should do a .get before doing a .put and echoing the token back (similar to how announce works).
> fix immutable put/gets

- test/horde.js
Before this change `t.end()` was being called prematurely which meant
that there was a small chance that a later test would use the same port
and send unexpected data
Example error: https://travis-ci.org/feross/bittorrent-dht/jobs/98983737
> test: improve reliability of horde tests

- README.md
- client.js
This allows us to abort DHT queries, since they can take huge amounts of time and discover absurdly high count of peers, in most cases we don't need that many but we may need to save traffic.
Refer to issue https://github.com/feross/bittorrent-dht/issues/92
@feross any ideas to how to implement the test for this?
> .lookup returns abort function

- README.md
This is a good option to have documented.
By the way, 16 might be too much for some old routers, as I've received actual complaints that routers/network crashes after the latest update of bittorrent-dht.
However, I'm going to bet that more than 99% of systems can handle 16 easily, and therefore it's not a viable concern. 
But it's good to have the option documented for anyone with issues
> Add 'concurrency' to opts documentation

- client.js
- test/dht_store_mutable.js
Added a way for peers to republish mutable content by allowing `DHT.put` to accept both signatures and a signing function as discussed #107
> Mutable content republication

- client.js
This was being silently dropped before.
> re-emit 'error' event from k-rpc module

- client.js
- package.json
- test/common.js
- test/internal.js
Use the new Buffer APIs from Node v6 for added security. For example,
`Buffer.from()` will throw if passed a number, unlike `Buffer()` which
allocated UNINITIALIZED memory in that case.
Use the `safe-buffer` package for compatibility with previous versions
of Node.js, including v4.x, v0.12, and v0.10.
https://github.com/feross/safe-buffer
> Use safe-buffer

- README.md
This prevents any peers from being missed by the listener
> Register 'peer' event handler before calling dht.lookup()

- client.js
- test/dht_store_mutable.js
BEP44:
> The salt can be any binary string (but probably most conveniently a hash of something). This string is appended to the key, as specified in the k field, when calculating the key to store the blob under (i.e. the key get requests specify to retrieve this data).
The salt should be appended to the key, This PR should fix #146
> Fix mutable put with salt.

- client.js
- package.json
Depends on https://github.com/mafintosh/k-rpc/pull/9
Fixes #164
Before: 689 kB
After: 163 kB
> Use `jssha` and `randombytes` packages in order to avoid large overhead of `crypto` in browserify build

- README.md
- client.js
I'm working on https://github.com/webtorrent/webtorrent/issues/288 and similarly to https://github.com/mafintosh/k-rpc/pull/8 I need to be able to provide a custom implementation of k-rpc.
> Allow specifying custom implementation of k-rpc

- client.js
- package.json
- test/updated-bucket.js
> #20 - check nodes on ping 

- client.js
Introduced in 20f52073205b036e44427c8f99c4dcb8bb015ca5, feels like as the result of rebase.
Property is already assigned few lines above.
> No need to assign `this._hash` twice

- README.md
- client.js
- test/announce.js
handle option maxAge to remove stale peers from peercache
>  peers: handle maxAge option

- README.md
Fixes missing `opts` parameter to `dht.get` method. @mafintosh
> Updated README with dht.get opts parameter details.

- client.js
This makes my life a bit simpler when interacting with `bittorrent-dht` since `Uint8Array` is supported in browser natively and `Buffer` is not.
Complements https://github.com/mafintosh/k-rpc/pull/15
https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView
> Add support for ArrayBufferView (like Uint8Array) in toBuffer() function

- client.js
- test/dht_store_mutable.js
- test/dht_test_vectors.js
- test/to-json.js
I'm testing DHT put with mutable value. The obvious problem is, we cached the value for mutable items, which means even it gets changed by other peers, we can't get the new value with current DHT instance.
> don't cache mutable value since it could be changed by other peers.

- test/dht_test_vectors.js
- test/put-get.js
> Fixed broken tests from #199.
